server:
  port: 9797
  servlet:  
      context-path: /health
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/healthcare
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
       ddl-auto: update